env:
  browser: true
  commonjs: true
  es6: true
  node: true
globals:
    graphql: true
extends: 
  - 'eslint:recommended'
  - idiomatic
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
plugins:
  - react
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  semi:
    - error
    - always
  one-var: 
    - error
    - never
  react/jsx-uses-react: 
    - error
  react/jsx-uses-vars: 
    - error
  no-console: 
    - warn
    - allow: 
        - warn 
        - error
